GreenPrint/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic.edit import CreateView
from password_reset import views as pwviews
from payplanner.views import signup, billender

urlpatterns = [
    url('^register/', signup, name="reg"),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout_then_login, name='logout'),
    url(r'^payplanner/', include('payplanner.urls')),
    url(r'^billender/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$', billender, name='billender'),
    url(r'', include('payplanner.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^recover/(?P<signature>.+)/$', pwviews.recover_done, name='password_reset_sent'),
    url(r'^recover/$', pwviews.recover, name='password_reset_recover'),
    url(r'^reset/done/$', auth_views.login, name='password_reset_done'),
    url(r'^reset/(?P<token>[\w:-]+)/$', pwviews.reset, name='password_reset_reset'),
]

payplanner/urls.py
#urls.py
# Created On: 9/5/2016
# Created By: Matt Agresta
#-----------------------------------------------------------#
#Set up Environment
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^config$', views.config, name='config'),
    url(r'^config/(?P<item_id>[0-9]+)/$',views.edit, name='edit'),
    url(r'settings$', views.account_mgmt, name='manage'),
]

payplanner/models.py
#Forms.py
# Created By: Matt Agresta
# Created On: 9/05/2016
# Holds classes for each payplanner model
#-----------------------------------------------------------#
from datetime import date

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

class Cycles(models.Model):
    
    """ Holds pay cycles e.g. Weekly, Bi-Weekly, Monthly """
    
    def __str__(self):
        return self.cycleName

    #Name of Cycle to be displayed on Input Forms
    cycleName = models.CharField(
         max_length=150,
         unique=True,
         verbose_name='Name'
    )

    
    #Cycle Duration
    cycleLength = models.IntegerField(
        verbose_name='Length of Cycle(Days)'
    )

    class Meta:
        
        verbose_name_plural = 'Pay Cycles'
        

class Categories(models.Model):

    """ Holds Expense Catgeory Information """
    
    def __str__(self):
        return self.catName
    
    #Name - To be displayed on Expense Input Form
    catName = models.CharField(
        max_length=150,
        unique=True,
        verbose_name='Category'
    )
    
    class Meta:
        
        verbose_name_plural = 'Expense/Income Categories'
        

class UserCat(models.Model):

    """ Holds List of Categories User would like on expenses form """
    
    user = models.OneToOneField(User)
    cats = models.ManyToManyField(Categories,
                                  verbose_name='Select Categories')

    
class Items(models.Model):

    """ Holds Expense and Income information for user """
    
    def __str__(self):
        return self.itemName
    
    #User who owns item
    user = models.ForeignKey(User)
    
    #Item Name Ex. Car Payment
    itemName = models.CharField(
         max_length=150,
         verbose_name='Name'
    )
    
    #Item type (expense or income)
    itemType = models.CharField(
        max_length=20,
        blank=True,
        verbose_name = 'Item Type'
    )
    
    #Category of item
    category = models.CharField(
        max_length=100,
        help_text='See Account Settings to modify choices!',
        null=True,
        blank=True,
    )
    
    #Ammount Due Ex 9999.99
    itemAmount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(1)],
        verbose_name='Amount'
    )
    
    #How Often expense is paid Ex One Time Only, Weekly, Monthly, Quarterly
    payCycle = models.ForeignKey(
        Cycles,
        to_field='cycleName',
        verbose_name='Pay Cycle',
    )
    
    #Hold day of the month expense is due
    nextDueDate = models.DateField(
        default=date.today().strftime('%m/%d/%Y'),
        verbose_name='Next Due Date',
    )
    
    #Hold end date of expense, not required.
    #Used if Expense is paid off, Ammount Changes
    endDate = models.DateField(
        blank=True,
        null=True,
        verbose_name='End Date (optional)',
    )

    #Holds serialize json representing date objects
    skiplst = models.TextField(
        blank=True,
        null=True,
    )
    
    #Holds Notes on expense. Ex. Account Number, Event description
    itemNote = models.CharField(
         max_length=400,
         blank=True,
         verbose_name='Notes (optional)'
    )
    
    class Meta:
        
        verbose_name_plural = 'Income/Expenses'
        


class BudgetData(models.Model):

    """ Holds line items for budget """
    
    def __str__(self):
        display = ('%s %s' % (self.parentItem.itemName,self.effectiveDate))
        return display

    #Item object used to create line
    parentItem = models.ForeignKey(
        Items,
    )

    #Amount of line item
    itemAmmount = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        validators=[MinValueValidator(1)],
        verbose_name='Amount'
    )
    #Hold effective date item
    effectiveDate = models.DateField(
        default=date.today,
    )

    #Any additional information for line item
    itemNote = models.CharField(
         max_length=400,
         blank=True,
         verbose_name='Notes'
    )

    class Meta:
        
        verbose_name_plural = 'Budget Data'


    @property
    def is_today(self):
       if date.today() == self.effectiveDate:
           return True
       return False


class BudgetProfile(models.Model):

    """ Holds settings for budget display """
    
    user = models.OneToOneField(User)
    
    budgetLength = models.IntegerField(
        validators=[MaxValueValidator(100), MinValueValidator(1)],
        verbose_name='Budget Length (Months)')
    
    histLength = models.IntegerField(
        validators=[MaxValueValidator(52), MinValueValidator(1)],
        verbose_name='Historical Length (Weeks)')

payplanner/views.py
#views.py
# Created On: 9/5/2016
# Created By: Matt Agresta
#-----------------------------------------------------------#
#Set up Environment
import ast
from datetime import date, datetime

from django.shortcuts import render,redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponse

from .forms import ExpensesForm, IncomeForm, EditForm, CategoriesForm
from .forms import UserCreateForm, UserCatForm, UserProfileForm
from .forms import BudgetProfileForm, UserProfileForm
from .models import Items, BudgetData, Categories, UserCat, BudgetProfile
from .budget import Budget
from .widgets import BillendarHTML


#Billender view     
@login_required
def billender(request, year, month):
    """ Displays budget in calender view """
    #Build HTML Calender
    form = EditForm()
    cal = BillendarHTML(6, request.user)
    billendar = cal.formatmonth(int(year),int(month))
    #Display in template
    temp = 'billender.html'
    c = {'billendar': billendar,
         'form': form}
    return render(request, temp, c)

#Function to load Expenses Form with previous Data
#Need to pass category added to this and set it in forminit
def expensesformload(request, **kwargs):
    #Grab Data from form before edit button was pressed
    formdata = request.POST['formdata']
    #Translate string back to dict
    formdata = formdata[11:]
    formdata = formdata[:-1]
    formdata = formdata.replace("[u","")
    formdata = formdata.replace("]","")
    forminit = eval(formdata)
    #Set initial category
    #Not working
    if 'category' in kwargs:
        cat = kwargs['category']
        forminit['category'] = cat
    #Load initial values into forms
    form = ExpensesForm(initial=forminit,
                        userid=request.user)
    return form


#Function to load UserCat Form
#To Be called by a view, returns form
def usercatformload(request):
    #Try and get UserCat object for user
    #Should have been created on user creation
    try:
        initcat = UserCat.objects.get(user=request.user)
        form = UserCatForm(instance=initcat)
    #If not Load form with initial value
    except:
        default = Categories.objects.get(catName='Other')
        default = [default,]
        form = UserCatForm(initial={'user':request.user,
                                    'cats':default})
    return form

#View to load and validate registration form
def signup(request):
    if request.method == 'POST':
        #Figure out which button was pressed
        #Options: add_income, add_expense, edit_item, delete_item
        if request.POST.get("submit"):
            form = UserCreateForm(request.POST)
            if form.is_valid():
                userid = form.save()
                #Log user in
                username = request.POST['username']
                password = request.POST['password1']
                user_obj = authenticate(username=username, password=password)
                #Create UserCat Object and add default cat of Other
                default = Categories.objects.get(catName='Other')
                usercat = UserCat(user=userid)
                usercat.save()
                usercat.cats.add(default)
                #Log user in and redirect to home page
                if user_obj.is_active:
                    login(request, user_obj)
                    # Redirect to a success page.
                    return redirect('home')
                #else - Disabled Account would go here
            #Registration Form Invalid    
            else:
                temp = 'register.html'
                footer = ''
                c = {'footer': footer,'form': form}
                return render(request, temp, c)
    else:
        form = UserCreateForm()
        temp = 'register.html'
        footer = ''
        c = {'footer': footer,
             'form': form}
        return render(request, temp, c)


#View to hold account management
@login_required
def account_mgmt(request):
    if request.method == 'POST':
        account_mgmt_btn = request.POST.get("account_mgmt_btn")
        #Button Options
        #save_form.Meta.name - Get Form Name and save
        if account_mgmt_btn == "Save User Categories":
            #If object exists for user update
            try:
                initcat = UserCat.objects.get(user=request.user)
                form = UserCatForm(request.POST, instance=initcat)
            #If not create one
            except:
                form = UserCatForm(request.POST)
            if form.is_valid():
                form.save()
                form = ''
                footer = ''
                #Variable to display menu buttons
                is_get = True
            #No Categories Selected
            else:
                footer = ''
                is_get = False            

            #Test if call came from ExpensesForm
            if request.POST['formdata']:
                temp = 'config.html'
                form = expensesformload(request)
                footer = 'Categories Updated'
                c = {'itemtype': 'Expense',
                     'form': form,
                     'footer': footer}
                
            #Called from /settings
            else:
                temp = 'manage.html'  
                c = {'is_get': is_get,
                     'form': form,
                     'footer':footer}
            return render(request, temp, c)

        #Save button on User Profile Form
        elif account_mgmt_btn == "Save User Profile":
            #Load Forms
            form = UserProfileForm(request.POST, instance=request.user)
            try:
                initcat = BudgetProfile.objects.get(user=request.user)
                form2 = BudgetProfileForm(request.POST, instance=initcat)
            except:
                form2 = BudgetProfileForm(request.POST)
            #Validate Forms    
            if form.is_valid() and form2.is_valid():
                form.save()
                form2.save()
                return redirect('home')
            #Invalid Form Selected
            else:
                footer = "Edit Your Profile"
                is_get = False            
                    
                temp = 'manage.html'  
                c = {'is_get': is_get,
                     'form': form,
                     'form2': form2,
                     'footer':footer}
                return render(request, temp, c)

        #Save button on User Profile Form
        elif account_mgmt_btn == "Save Category":
            form = CategoriesForm(request.POST)
            if form.is_valid():
                cat = form.save()
                #Add Category to user cats
                usercat = UserCat.objects.get(user=request.user)
                usercat.cats.add(cat)
                footer = 'Category Added'
                #If formdata exist, call came from ExpensesForm
                if request.POST['formdata']:
                    form = expensesformload(request, category=cat)
                    temp = 'config.html'
                    footer = 'Categories Updated'
                    c = {'itemtype': 'Expense',
                         'form': form,
                         'footer': footer}
                else:
                    temp = 'manage.html'  
                    #Load UserCatForm
                    #Try and get UserCat object for user
                    try:
                        initcat = UserCat.objects.get(user=request.user)
                        form = UserCatForm(instance=initcat)
                    #If not Load form with initial value
                    except:
                        default = Categories.objects.get(catName='Other')
                        default = [default,]
                        form = UserCatForm(initial={'user':request.user,
                                                    'cats':default})
                    c = {'form': form,'footer':footer}
                    
            else:
                temp = 'manage.html'
                footer = 'Form Invalid'
                c = {'form': form,'footer':footer}
                
            #Render form with context
            return render(request, temp, c)

        #Add Category Button - Depricated
        #Replaced with modal (form3) on Edit Cateogries 
        elif account_mgmt_btn == "Add Category":
            form = CategoriesForm()
            footer = 'Add Category'
            temp = 'manage.html'  
            c = {'form': form,'footer':footer}
            if request.POST.get('formdata'):
                nextform = request.POST.get('formdata')
                c = {'form': form,'footer':footer, 'nextform':nextform}
            
            return render(request, temp, c)
            
        #Cancel - redirect back to this view
        elif account_mgmt_btn == "Cancel":
            temp = 'manage.html'
            footer = ''
            is_get = True
            c = {'is_get': is_get,
                 'footer':footer}
            #If formdata exist, call came from ExpensesForm
            if request.POST['formdata']:
                form = expensesformload(request)
                temp = 'config.html'
                footer = 'Categories Updated'
                c = {'itemtype': 'Expense',
                     'form': form,
                     'footer': footer}
            return render(request, temp, c)

        #Edit Profile button pressed
        elif account_mgmt_btn == "Edit Profile":
            #Load UserProfileForm
            form = UserProfileForm(instance=request.user)
            #Load BudgetProfileForm
            try:
                initcat = BudgetProfile.objects.get(user=request.user)
                form2 = BudgetProfileForm(instance=initcat)
            except:

payplanner/templates/base.html
{% load staticfiles %}
<html>
<head>
 <!--Import Google Icon Font-->
   <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


 <!--Import jquery CSS-->
   <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
 <!--Import materialize.css-->
   <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}" media="screen,projection"/>
 <!--Import Custom CSS to formate widgets-->
   <link rel="stylesheet" href="{% static 'admin/css/widgets.css' %}" />
   <link rel="stylesheet" href="{% static 'css/selector.css' %}">
   <link rel="stylesheet" href="{% static 'css/budget.css' %}">
 <!--Import materialize.css-->
   <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
   <link rel="stylesheet" href="{% static 'css/budget.css' %}">


 
<!--Import materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>

<!--Import local jquery scripts for filtered multiple select-->
   <script type="text/javascript" src="{% static 'js/jsi18n.js' %}"></script>
   <script type="text/javascript" src="{% static 'admin/js/jquery.min.js' %}"></script>
   <script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
   
<!--JS for home page table formatting -->
<script type="text/javascript" src="{% static 'js/formload.js' %}"></script>

<!--Form Media -->
{{ form.media }}

<!--Initialize select boxes and date pickers -->
<script>
 
 $(document).ready(function() {
    $( '#id_category' ).material_select();
    $( '#id_payCycle' ).material_select();
    $('.datepicker').pickadate({
    	selectMonths: true, // Creates a dropdown to control month
    	selectYears: 15, // Creates a dropdown of 15 years to control year
        format: 'mm/dd/yyyy',
        onSet: function( arg ){
            if ( 'select' in arg ){ //prevent closing on selecting month/year
                 this.close();
            }
        }
    });
  });
 
  $(document).ready(function(){
    //Add depth to budget line on hover and see if toast should be shown
     $('[id^="budget-line"]').hover(function() {
        showToast($(this));
        $(this).addClass("z-depth-1 amber lighten-5");
        }, function(){
        $(this).removeClass("z-depth-1 amber lighten-5"); 
     });

    //Highlight first row with current day
     $('[name="True"]:first').addClass("teal lighten-4");
    
     //Load modal with calendar day
     $( ".modal-trigger-expand-day" ).click(function() { 
        loadCalDayModay($(this).parent().parent()); 
        $('#modal_expand_day').openModal();
     });

    //Load modal with edititem form
     $( ".modal-form-trigger" ).click(function() { 
        loadModalForm('#modalform',$(this)); 
        $('#modal1').openModal();
     }); 

    //Load tooltips
     $('.budget-header').tooltip({delay: 50});
   
    //Load other modals
     $('.modal-trigger').leanModal(); 
  
    //Update date select on semi monthly
     $('#id_payCycle').change(function() {
        autoDate('#id_nextDueDate',$(this));
     });
    
     //mobile formatting  
     if($(document).width() < 500){
        mobileformat();
     }
   
  });
  
 </script>
 
 <!--Let browser know website is optimized for mobile-->
   <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
{% block title %}{% endblock %}
 <!-- Favicon -->
<link rel="shortcut icon" href="{% static 'pics/GP_icon.ico' %}" type="image/x-icon"/>
<link rel="icon" href="{% static 'pics/GP_icon.ico' %}" type="image/png" sizes="160x160"/>
<link rel="shortcut icon" href="{% static 'pics/GP_icon.png' %}" type="image/png" sizes="160x160"/>
<link rel="apple-touch-icon" sizes="57x57" href="{% static 'pics/GP_icon.png' %}" />
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'pics/GP_icon.png' %}" />
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'pics/GP_icon.png' %}" />
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'pics/GP_icon.png' %}" />
</head>
<body class="grey lighten-4">
<div class="container">
  <div id="header_row" class="row">
    <div class="col s12">
      <div id="header_card" class="card page-header z-depth-3">
       <div id="header_content" class="card-content center">
        <span class="card-title"><a id="page_header" title="PayPlanner Home" href="{% url 'home' %}" class="amber-text text-darken-1 page-header">GreenPrint PayPlanner</a></span>
       </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col s12">{% block content %}{% endblock %}</div>
  </div>
  <div class="row">
    <div class="col s12">{% block footer %}{% endblock %}</div>
  </div>
 </div>
</body>
</html>

payplanner/templates/billender.html
{% extends "base.html" %}
{% comment %}
billendar template
Author: Matt Agresta
Created on: 12/16/2016
Will hold form to display budget in calendar format

{% endcomment %}
{% block title %}
<title>PayPlanner Budget</title>
{% endblock %}
{% block content %}
<div class="container-fluid">
  <form id="billender_form" action="{% url 'config' %}" method="post">
    {% csrf_token %}
 <div class="row">
  <div class="col s12">
   <div class="card-panel z-depth-2">
    
    {{ billendar}}
   
   </div>
  </div>
 </div>
 </form>

<!-- Modal Structure --> 
       <div id="modal1" class="modal modal-fixed-footer"> 
          <div class="modal-content"> 
            <h4>Edit Item</h4>
            <h5 id="subhead"></h5> 
            <form id="modalform" action="/config/" method="post"> 
             {% csrf_token %}
             {{ form }} 
             <div id="radios" class="radio"> 
              <input title="Apply Changes to this line only" id="single" type="radio" name="edit_opt" value="single"
checked="checked"> 
              <label for="single">This date only</label> 
              <input title="Apply Changes to this line and future dates"id="future" type="radio" name="edit_opt" value="future"> 
              <label for="future">Future</label> 
              <input title="Apply Changes to all lines like this" id="all" type="radio" name="edit_opt" value="all"> 
              <label for="all">All</label> 
             </div> 
          </div> 
          <div class="modal-footer"> 
              <input type="hidden" name="cur_date" value="" />
              <input type="hidden" name="prev_page" value="billender" />
              <input type="submit" name="edit_btn" value="Update" class="btn"/> 
              <input type="submit" name="edit_btn" value="Delete" class="btn"/> 
              <a href="#" class="modal-action modal-close btn"/>Cancel</a>
          </div> 
       </div> 
<!-- End of Modal --> 

<!-- Modal Structure --> 
       <div id="modal_expand_day" class="modal modal-fixed-footer"> 
          <div class="modal-content"> 
           <h3 id="daynum"></h3>
           <hr />
           <a href="#modal1" class="btn modal-trigger">Test</a>
           <div id="budget-items"></div>
          </div> 
          <div class="modal-footer"> 
            <input type="hidden" name="cur_date" value="" />
            <input type="hidden" name="prev_page" value="billender" />
            <button name="config_btn" value="Add Income" class="btn budget-header teal lighten-2 tooltipped" data-position="bottom" data-delay="50" data-tooltip="Add Income"><i class="material-icons">add</i>Income</button>
            <button name="config_btn" value="Add Expense" class="btn budget-header teal lighten-2 tooltipped" data-position="bottom" data-delay="50" data-tooltip="Add Expense"><i class="material-icons">add</i>Expense</button>
          </div> 
       </div> 
<!-- End of Modal --> 

<!-- FAB -->
<div class="fixed-action-btn">
    <a class="btn-floating btn-large teal">
      <i class="large material-icons">view_module</i>
    </a>
    <ul>
      <li><a class="btn-floating teal" href="/"><i class="material-icons">toc</i></a></li>
      <li><a class="btn-floating teal" href="{% url 'manage' %}"><i class="tiny material-icons">settings</i></a></li>
      <li><a id="logout" class="btn-floating teal" href="{% url 'logout' %}"><i id="logout_icon" class="material-icons right">exit_to_app</i></a></li>
    </ul>
  </div>
</div>
<!-- End of Modal --> 
</div>
{% endblock %}
{% block footer %}
{{ footer }}
{% endblock %}

payplanner/templates/config.html
{% extends "base.html" %}
{% comment %}
Item Add template
Author: Matt Agresta
Created on: 9/4/2016
{% endcomment %}

{% block title %}
<title>Add {{ itemtype }}</title>
{% endblock %}

{% block content %}
<div class="container-fluid">
 <form action="{% url 'config' %}" method="post">
      {% csrf_token %}
   <div class="row form">
      {% for hidden in form.hidden_fields %}
     <div class="col s12">{{ hidden }}</div>
      {% endfor %}
   </div>
   <div class="row">
      {% for field in form.visible_fields %}
     <div class="input-field col s12 l6">
        {{ field.errors }}
        {{ field }}
        <label class="active" for="{{ field.name }}">{{ field.label }}</label>
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
     </div>
     {% endfor %}
   </div>
   <div class="row center">
     <div class="col s12 l6 push-l3">
       <input type="hidden" name="prev_page" value="{{ prevpage }}" />
<input type="hidden" name="cur_date" value="{{ curdate }}" />
       <input type="submit" name="config_btn" value="Save {{ itemtype }}" class="btn"/>
       <input type="submit" name="config_btn" value="Cancel" class="btn"/>
     </div>
   </div>
 </form>
</div>
{% endblock %}

{% block footer %}
<div class="center">{{ footer }}</div>
{% endblock %}

payplanner/templates/edititem.html
{% extends "base.html" %}
{% comment %}
Item edit template
Author: Matt Agresta
Created on: 9/4/2016
TODO:
Add if statement to read variable to see if income or expense and
put correct title
{% endcomment %}

{% block title %}
<title>Edit {{ name }}</title>
{% endblock %}

{% block content %}
<div class="container-fluid">
 <form action="{% url 'edit' itemid %}" method="post">
  <div class="row">
 {% if notsingle %}
  <div class="col s6 m8">
 {% else %}
  <div class="col s12 m6 push-m3">
 {% endif %}
    <div class="card">
     <div class="card-content">
       <span class="card-title">{{ name }} - {{ date }}</span>
       {% csrf_token %}
       {{ form.as_p }}
     </div>
    </div>
   </div>
 {% if notsingle %}
   <div class="col s6 m4">
    <div class="card">
     <div class="card-content">
       <span class="card-title">Apply to:</span>
       <div id="radios" class="radio">
        <input title="Apply Changes to this line only" id="single" type="radio" name="edit_opt" value="single" checked="checked">
        <label for="single">{{ date }} only</label> 
        <input title="Apply Changes to this line and future dates"id="future" type="radio" name="edit_opt" value="future"> 
        <label for="future">{{ date }} and on</label>
        <input title="Apply Changes to all lines like this" id="all" type="radio" name="edit_opt" value="all"> 
        <label for="all">All {{ name }}</label>
       </div>
     </div>
    </div>
   </div>
 </div>
 {% endif %}
 <div class="row">
   <div class="col s12 center">
     <input type="submit" name="edit_btn" value="Update" class="btn"/>
     <input type="submit" name="edit_btn" value="Delete" class="btn"/>
     <input type="submit" name="edit_btn" value="Cancel" class="btn"/>
   </div>
 </div> 
</form>
</div>
{% endblock %}
{% block footer %}
{{ footer }}
{% endblock %}

payplanner/templates/register.html
{% extends "base.html" %}
{% comment %}
User Registration template
Author: Matt Agresta
Created on: 9/21/2016

{% endcomment %}

{% block title %}
<title>User Registration</title>
{% endblock %}

{% block content %}
<div class="col s12 m6 push-m3">
  <div class="card">
    <div class="card-content">
      <span class="card-title">Please Register</span>
    </div>
    <div class="card action"> 
      {%if form.errors %}
      <p> Invalid username/password combination, please try again </p>
      {% endif %}
      <form action="{% url 'reg' %}" method="post" class="regform">
      {% csrf_token %}
      {{ form }}
    </div>
  </div>
  <div class="valign-wrapper">
      <input type="submit" id="submit" name="submit" value="Sign in" class="btn valign"/>
      <input type="hidden" name="next" value="{{ next }}" />  
  </div>      
      </form>
</div>
{% endblock %}
{% block footer %}
{{ footer }}
{% endblock %}